image: node:16

stages:
  - build
  - test
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - ssh $SSH_USER@$SSH_HOST "mkdir -p /var/www/myapp"
    - rsync -avz --delete-after --exclude 'node_modules' ./ $SSH_USER@$SSH_HOST:/var/www/myapp/
    - ssh $SSH_USER@$SSH_HOST "cd /var/www/myapp && npm install --production && pm2 restart app.js"
  only:
    - main
  environment:
    name: production
