image: node:16 # Use Node.js image; adjust version as needed

stages:
  - build
  - test
  - deploy

# Install dependencies
install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

# Run tests (if you have tests)
test:
  stage: test
  script:
    - npm test # Ensure you have a test script defined in package.json
  only:
    - main

# Deploy your application
deploy:
  stage: deploy
  script:
    - node app.js # Start your application
  only:
    - main
